### ISSUE TITLE
[MacOS Ventura] Segfault / Crashes, apparently due to Emacs version. Workaround in comments

### ISSUE THREAD

**Issue by abdalazizrashid** [vedang/pdf-tools#166]
When using a dark theme, any attempt to highlight text result in immediate segfault

**Comment by vedang** [comment]
I cannot reproduce this bug. Please test it with vanilla Emacs and see if you can reproduce the problem. If the problem persists, please share your Emacs version. pdf-tools and poppler versions.

**Comment by abdalazizrashid** [comment]
https://user-images.githubusercontent.com/33545649/199521562-2ac1e3ee-57d9-46b6-97e5-abba223708e9.mov

poppler: stable 22.08.0
GNU Emacs 29.0.50

**Comment by haji-ali** [comment]
I am also experiencing the same issue on MacOS, though I am not sure it is related to the theme. 

See here for a crash log:
https://gist.github.com/haji-ali/8886548616327d0cc58f3b659eaa036c

**Comment by ismama** [comment]
I observe the same behavior on my machine w/ MacOs 13.0.1
pdf-tools: 20221007.1404
poppler: stable 22.08.0
GNU Emacs 29.0.50

**Comment by orgtre** [comment]
I also see the same behavior, with the same setup as ismama and across a bunch of dark themes I tested. However, Emacs doesn't crash when `pdf-view-dark-minor-mode` is enabled, so that can work as a workaround for now.

**Comment by haji-ali** [comment]
@orgtre, thanks! `pdf-view-dark-minor-mode` does fix the issue for me.

**Comment by vedang** [comment]
This is really strange, because `pdf-view-dark-minor-mode` does not actually have anything to do with dark vs light themes, and should have no effect. For the people being impacted by this bug, can you please do the following? 

1. Share your OS, Emacs and poppler versions 
2. Share your `pdf-tools` version. You can do this by `M-x package-list-packages` -> Search for `pdf-tools` -> Hit Enter and copy all the details that pop up in the Help buffer
3. Share your custom configuration for `pdf-tools` 
4. Share a backtrace / stacktrace for the crash.

**Comment by simurgh9** [comment]
[Here](https://github.com/vedang/pdf-tools/issues/173#issuecomment-1341882242) is a temporary hook for the minor mode.

**Comment by d8660091** [comment]
It has something to do with the following function invocation, which was invoked twice in sequential inside "pdf-isearch-current-colors" function
```
(delete-frame f)
```

I can reproduce the issue with just:
```
(add-hook 'pdf-tools-enabled-hook (lambda ()
                                    (pdf-util-face-colors 'pdf-isearch-match nil)
                                    (pdf-util-face-colors 'pdf-isearch-lazy nil)))
```
And run "pdf-tools-install"

I tried adding (sit-for 1) before  (delete-frame f), the crash was gone.

But I am still not sure what's really happening

**Comment by d8660091** [comment]
Ok, I found a neater way to crash my Emacs:

```
(progn
  (delete-frame (x-create-frame-with-faces))
  (delete-frame (x-create-frame-with-faces))
)
```

**Comment by vedang** [comment]
Interesting. I can re-create this on Emacs on M1 MacOS 12.6 (`GNU Emacs 29.0.50 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6 (Build 21G115)) of 2022-10-12`) , but it works correctly on Emacs 28 (`GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2022-09-12
`) for the same machine.

**Comment by d8660091** [comment]
To give a datapoint, it crashes on my M2 28.2. `GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2022-09-12`

**Comment by Pepito-source** [comment]
> This is really strange, because `pdf-view-dark-minor-mode` does not actually have anything to do with dark vs light themes, and should have no effect. For the people being impacted by this bug, can you please do the following?
> 
> 1. Share your OS, Emacs and poppler versions
> 2. Share your `pdf-tools` version. You can do this by `M-x package-list-packages` -> Search for `pdf-tools` -> Hit Enter and copy all the details that pop up in the Help buffer
> 3. Share your custom configuration for `pdf-tools`
> 4. Share a backtrace / stacktrace for the crash.

Hi [vedang](https://github.com/vedang), thanks for maintaining and developing pdf-tools. 

- OS: `MacOS Ventura 13.2.1`
- Emacs: `GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2023-02-22`
- Poppler: `poppler 23.03.0`
- pdf-tools: doom emacs `(package! pdf-tools :pin "bc2ba117e8c3196ff9adf0da4fa1e63a8da3d7c8")`
- custom config: added `export PKG_CONFIG_PATH="/opt/local/lib/pkgconfig"` to my .zshrc file. Without it, I couldn't compile the epdfinfo server
- Crash backtrace: [here](https://gist.github.com/Pepito-source/d452b52421fce811fd20be72e58b2bbd)

**Comment by haji-ali** [comment]
An update regarding this issue.

After updating to latest MacOS (Ventura 13.3) and, very important, recompiling emacs (I use emacs-plus) the problem seems to disappear for emacs 28.2 and 29.0.60. At least pdf-tools and the test by @d8660091  no longer cause a crash.

**Comment by milanglacier** [comment]
> An update regarding this issue.
> 
> After updating to latest MacOS (Ventura 13.3) and, very important, recompiling emacs (I use emacs-plus) the problem seems to disappear for emacs 28.2 and 29.0.60. At least pdf-tools and the test by @d8660091 no longer cause a crash.

I upgraded to 13.3.1 today and I recompiled emacs-plus 28 after upgrading to ventura.  But the segfault also happens when making selection for the text.

the above mentioned workaround works for me though:

```lisp
(defun my:pdf-midnight-mode-maybe ()
    (when (eq (frame-parameter nil 'background-mode) 'dark)
        (pdf-view-midnight-minor-mode)
        (pdf-view-dark-minor-mode)))
;; add this function to pdf-mode-hook
```

**Comment by vedang** [comment]
I've made changes to `pdf-tools` to automatically enable `pdf-view-dark-minor-mode` if the current Emacs theme is dark. Closing this issue now since the workaround is baked into the code. 

Goes without saying that it would still be good to know why the `delete-frame` call is causing Emacs to segfault. If anyone has more information here, please add!

**Comment by milanglacier** [comment]
I still need to manually add those lines in my config to avoid the segfault error after `d1d331a`, the auto activation of `pdf-view-dark-minor-mode` seems not work.  

```lisp
(defun my:pdf-midnight-mode-maybe ()
    (when (eq (frame-parameter nil 'background-mode) 'dark)
        (pdf-view-midnight-minor-mode)
        (pdf-view-dark-minor-mode)))

(add-hook 'pdf-view-mode-hook #'my:pdf-midnight-mode-maybe)
```

**Comment by vedang** [comment]
@milanglacier : In `d1d331a`, the mode is being activated when enabling `pdf-view-mode`, based on the theme at that time. I haven't handled the case of the user changing the theme after a PDF was loaded (which the workaround in your comment does not handle either). 

Can you check if the mode is enabled on your setup? You can do this by running `C-c C-d` once the PDF is loaded (which toggles `pdf-view-dark-minor-mode` and should *disable* the mode since `d1d331a` would have *enabled* it by default). 

You can also run `C-h v pdf-tools-enabled-modes` after opening a PDF which should show you a list with `pdf-view-dark-minor-mode` as the first entry.
