### ISSUE TITLE
Please create wiki for extra documentation

### ISSUE THREAD

**Issue by dalanicolai** [vedang/pdf-tools#38]
I've been looking a little into how pdf-tools works. And it is not so straightforward because it is a nifty package and many functions lack docstrings. So to keep track of my findings, I have created a wiki in my fork of this repo [here](https://github.com/dalanicolai/pdf-tools/wiki).

However, it might be handier to create the wiki over here, where we can 'log' about the reverse engineering, it could save us a lot of time.
Anyway, I will continue writing my notes on that wiki (slowly, because time is scarce), and you can do with it whatever you like (copy, link, nothing:)

Anyway, just notifying you about it.

As I wrote already [here](https://github.com/vedang/pdf-tools/issues/18#issuecomment-890522105), I think/showed it should be possible to get real continuous scrolling (also without using pymupd), which is the reason why I am looking more into the package.

**Comment by vedang** [comment]
Thank you for starting this effort. I myself am building a Wiki and website for `pdf-tools`, as part of reducing the number of queries I get about the same things and as part of understanding the code better. 

The aim is to build a User Manual as well as a Developer / Hacker manual for `pdf-tools`. 

I will be very happy to incorporate your notes when the time is right. Leaving this issue open until then so that others can find your notes.
