### ISSUE TITLE
Provide a {top,bottom}-of-page functions / Readme misleading

### ISSUE THREAD

**Issue by GregorZattler** [vedang/pdf-tools#40]
Navigating larger-than-display PDFs is cumbersome: If in the middle of a page pdf-view-next-page-command takes you to the same position on the next page, commands for going to top-left, top-right, bottom-left, bottom-right  corner of (next) page would be helpful.

The Readme.org says:
"Top of Page / Bottom of Page | < / >"
while actually these keys are bound to first page, last page respectively, there is no top-of-page command etc.

Thanks for all, who work(ed) on pdf-tools, Gregor

**Comment by orgtre** [comment]
Thanks for pointing this out, the readme is indeed wrong.

There are quite a few functions related to scrolling around pdf pages (= images) already. The following two commands work smoothly as long as the whole page fits horizontally:

pdf-view-scroll-scroll-down-or-previous-page (DEL, delete/backspace)
pdf-view-scroll-up-or-next-page (SPC, spacebar)

Otherwise, image-mode, whose commands are loaded by PDFView, provides a few useful commands:
image-scroll-right (C-x >)
image-scroll-left (C-x <)
image-scroll-up (C-v)
image-scroll-down (M-v)
image-forward-hscroll (C-f, <right>)
image-backward-hscroll (C-b, <left>)
image-bob
image-eob
image-eol
image-bol 

You can use "M-x describe-function COMMANDNAME" (C-h f) to read about their differences and see what keys they are bound to in your Emacs (defaults are in parenthesis above). I agree that for pdfs that don't fit horizontally, it might still be nice to have two commands that intelligently scroll back and forth along a natural reading path (especially with two-column pdfs).

Removing the lines with [remap beginning-of-buffer] and [remap end-of-buffer] where pdf-view-mode-map is defined, would restore the image-mode-map remappings of these to image-bob and image-eob, which pdf-view-mode-map inherits (but then overwrites). Then the readme would be correct again. On the other hand these functions are kind of superseded by pdf-view-scroll-scroll-down-or-previous-page and pdf-view-scroll-up-or-next-page.

**Comment by GregorZattler** [comment]
Thanks for pointing out the image-scroll or movement commands.  I knew that the PDF is presented as an image but did not realise that there are commands related to the pages as images. That helps a lot, especially now that I realise that e.g. image-eob jumps to the bottom of the image, not the last page of the PDF.

Perhaps that could be mentioned in the Readme.org?

Regarding 

> intelligently scroll back and forth along a natural reading path

My use case is reading a newspaper: six columns per page, pages too large / script too small to read with the whole page shown even at a 32" monitor.  At my 12,5" laptop display I can read comfortable with 3 columns shown, but that involves a lot of scrolling :-)

**Comment by tongjie-chen** [comment]
After some testing, I found the scroll command to get to top, bottom, left and right as following:

Top 
```(image-set-window-vscroll 0)```

Bottom
```(image-set-window-vscroll (- (cdr (pdf-view-image-size)) (- (elt (pdf-util-image-displayed-edges) 3) (elt (pdf-util-image-displayed-edges) 1))))```

Left
```(image-set-window-hscroll 0)```

Right does not work the same way as it is scrolling in column width.
```(image-set-window-hscroll (/ (- (car (pdf-view-image-size)) (- (elt (pdf-util-image-displayed-edges) 2) (elt (pdf-util-image-displayed-edges) 0))) (frame-char-width)))```

You can make the following key map to get to top with "z w", bottom` "z s", left "z a" and right "z d".
```emacs-lisp
(define-key pdf-view-mode-map (kbd "z w") (lambda() (interactive) (image-set-window-vscroll 0)))
(define-key pdf-view-mode-map (kbd "z s") (lambda() (interactive) (image-set-window-vscroll (- (cdr (pdf-view-image-size)) (- (elt (pdf-util-image-displayed-edges) 3) (elt (pdf-util-image-displayed-edges) 1))))))
(define-key pdf-view-mode-map (kbd "z a") (lambda() (interactive) (image-set-window-hscroll 0)))
(define-key pdf-view-mode-map (kbd "z d") (lambda() (interactive) (image-set-window-hscroll (/ (- (car (pdf-view-image-size)) (- (elt (pdf-util-image-displayed-edges) 2) (elt (pdf-util-image-displayed-edges) 0))) (frame-char-width)))))
```

**Comment by GregorZattler** [comment]
Hi Tongjie,
* Tongjie Chen ***@***.***> [2021-08-31; 07:39]:
> After some testing, I found the scroll command to get to
> top, bottom, left and right as following:
[...]

thanks.  Going to the right or left side was already
possible with image-bob and image-eob, bound to C-a and C-e
in pdf-view-mode, respectively.

New and really helpful for reading a hughe newspaper page
with -- in my case -- six columns, are the commands for
moving up and down.  I'll bind them to C-<prior> and
C-<next>.

Thank you very much, Gregor

**Comment by vedang** [comment]
I've labeled this ticket as documentation to track this as a documentation improvement. Will close the ticket once I update the README
