### ISSUE TITLE
How to contribute to the wiki/readme?

### ISSUE THREAD

**Issue by dalanicolai** [vedang/pdf-tools#65]
Thanks for the nice work on the wiki, it looks good. It would be nice if it had some search functionality, but as the wiki is created from the README, we can search just in the README also (even better locally with swoop/swiper etc.).

I have read the instructions in the [pdftoolswiki README](https://github.com/vedang/pdftoolswiki), but when I open the pdf-tools README , I find that all headings have a set of properties now (I think since commit 69e06e226844a12369e5b7d0bc561bcdeea8b4b3). So I was wondering if there is some special way for adding sections to the README, or can I just add headings without the properties? Would be nice if the answer here could get added to the instructions in the [pdftoolswiki README](https://github.com/vedang/pdftoolswiki) also.

**Comment by vedang** [comment]
Hey @dalanicolai,

Thanks! The only requirement is to create normal IDs in the org files. So if you create a new heading in the `README.org` file, you should just run `M-x org-id-get-create` on in. For referencing different sections, you should use `id:` links. Once you do this, everything else is auto-generated. This is equivalent to writing notes using [`org-roam`](https://github.com/org-roam/org-roam)

Additionally, if you are a user of [`org-brain`](https://github.com/Kungsgeten/org-brain), then you can also add parent/child relationships using the `brain-child:` and `brain-parent:` link types.

I haven't publicized the Wiki much yet, because I want to add some notes under `docs/*.org` as well. (Such as `interacting with the server`, pulling out features into their own file etc). Feel free to contribute at whatever place you feel write, I will give feedback / make the necessary changes.

I'll add this note to the Wiki README as well.

**Comment by dalanicolai** [comment]
That sounds easy enough. Thanks for the quick reply! Nice work!
