### ISSUE TITLE
Mention elpa-pdf-tools-server in the README

### ISSUE THREAD

**Issue by minad** [vedang/pdf-tools#79]
This package is available on Debian and Ubuntu. There is no need for manual compilation if this package is installed via apt-get.

**Comment by vedang** [comment]
There is no need for manual compilation at all, since this package (elisp + self build) is also available via Melpa. However, the instructions are useful to people with non-standard installation methods. Eventually, I will clean up the documentation some more and move these instructions out of the main README into separate docs. Similarly, I'll add a note about installing the epdinfo server via `apt-get`. However, this is also a non-standard and unsupported installation mechanism since I don't control the version of the server shipped in the package manager.

**Comment by minad** [comment]
Thanks!
